publishers:
  chat:
    topic: "chat"
    queue_size: 100
    latch: false
subscribers:
  chat:
    topic: "/bob/chat"
    queue_size: 100
    latch: false
servers:
  call:
    service: "call"
chat:
  initiate: True
  say: "Hello Bob!"
  