publishers:
  chat:
    topic: "chat"
    queue_size: 100
    latch: false
    diagnostics:
      message_latency:
        window_size: 100
subscribers:
  chat:
    topic: "/bob/chat"
    queue_size: 100
    latch: false
servers:
  call:
    service: "call"
chat:
  name: "Alice"
  initiate: True
  say: "Hello Bob!"
  