publishers:
  chat:
    topic: "chat"
    queue_size: 100
subscribers:
  chat:
    topic: "/alice/chat"
    queue_size: 100
servers:
  call:
    service: "call"
chat:
  name: "Bob"
  initiate: False
  say: "Hello Alice!"
