pub_rate: 1.0
base_path: ''
analyzers:
  workers:
    type: AnalyzerGroup
    path: Workers
    analyzers:
      house_keeping:
        type: GenericAnalyzer
        path: House Keeping
        find_and_remove_prefix: "maya: house_keeping"
      fanning:
        type: GenericAnalyzer
        path: Fanning
        find_and_remove_prefix: "maya: fanning"
      nursing:
        type: GenericAnalyzer
        path: Nursing
        find_and_remove_prefix: "maya: nursing"
      collecting:
        type: GenericAnalyzer
        path: Collecting
        find_and_remove_prefix: "maya: collecting"
