subscribers:
  wake_nursing:
    topic: "/wake_nursing"
    queue_size: 100
    latch: false

workers:
  house_keeping:
    rate: 10
    autostart: true
  fanning:
    rate: 100
    autostart: true
  nursing:
    rate: 20
    autostart: true
  collecting:
    rate: 1000
    autostart: true
field:
  flowers: 10000
