subscribers:
  wake_nursing:
    topic: "/wake_nursing"
    queue_size: 100
    latch: false

workers:
  house_keeping:
    rate: 10
    autostart: true
  fanning:
    rate: 100
    autostart: true
  nursing:
    rate: 20
    autostart: true
    diagnostics:
      frequency:
        mean_tolerance:
          warn: 0.1
          error: 0.2
        standard_deviation_tolerance:
          warn: 0.25
          error: 0.5
  collecting:
    rate: 1000
    autostart: true
    private_callback_queue: true
    priority: 99

diagnostics:
  period: 1.0
    
field:
  flowers: 100000
