time stamp_of_last_event      # Timestamp of last event

uint32 num_samples            # Number of non-rolling samples
float32 min                   # Minimum frequency in [Hz]
float32 max                   # Maximum frequency in [Hz]

uint32 num_rolling_samples    # Number of rolling samples
float32 rolling_mean          # Rolling mean frequency in [Hz]
float32 rolling_variance      # Rolling frequency variance in [Hz^2]
