time stamp_of_last_event      # Timestamp of last event

uint32 num_samples            # Number of non-rolling samples
float32 min                   # Minimum period in [s]
float32 max                   # Maximum period in [s]

uint32 num_rolling_samples    # Number of rolling samples
float32 rolling_mean          # Rolling mean period in [s]
float32 rolling_variance      # Rolling period variance in [s^2]
